name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Setup Python 3.12
      #   id: setup-python
      #   uses: actions/setup-python@v5
      #   with:
      #   python-version: "3.12"
      #   cache: 'pip'
      #   cache-dependency-path: code/requirements.txt
      # - run: |
      #     cd code && pip install -r requirements.txt
      #     cd ..
      #     zip -r capa_lambda.zip capa_lambda
      
      - name: Connect to AWS
        id: connect-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: awssyncsession
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Get secret value from AWS Secrets Manager
        run: |
          secret_value=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.NAME_SECRET_MANAGER }} --query SecretString --output text)
          echo "$secret_value" | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\""' >> "./terraform.tfvars"

      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@v1.2.0
        with:
          terraform_version: '1.10.5'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.NAME_BUCKET_TERRAFORM }}"

      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply --auto-approve 