name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read 

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Connect to AWS
        id: connect-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Get secret value from AWS Secrets Manager
        run: |
          secret_value=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.NAME_SECRET_MANAGER }} --query SecretString --output text)
          echo "$secret_value" | jq -r '
          to_entries | .[] | 
          if .value | test("^\\{.*\\}$") then 
            "\(.key) = \(.value | gsub("\""; "\""))" 
          elif .value | test("^\\[.*\\]$") then 
            "\(.key) = \(.value | gsub("\""; "\""))" 
          else 
            "\(.key) = \"\(.value)\""
          end
          ' >> "./terraform.tfvars"
          cat ./terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10.5'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.NAME_BUCKET_TERRAFORM }}"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply --auto-approve
